# Generated by Django 5.2.10 on 2026-03-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_media_platform_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.platform'),
            preserve_default=False,
        ),
    ]
